# pubspec.yaml

name: vista_guide
description: "AI Travel Companion for Exploration and Insights."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # For API calls
  http: ^1.2.0
  
  # For Gemini AI integration
  google_generative_ai: ^0.4.6

  # For location services
  location: ^6.0.2
  
  # For weather data
  geolocator: ^13.0.1
  geocoding: ^3.0.0

  # For managing environment variables (API key)
  flutter_dotenv: ^5.1.0

  # For displaying images from URLs
  cached_network_image: ^3.3.1

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^6.0.0

  # For navigation
  go_router: ^16.0.0
  
  # For URL launching
  url_launcher: ^6.3.1

  # For image picking and storage
  image_picker: ^1.1.2
  path_provider: ^2.1.4

  # For offline storage
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/models/
